---
development:
  DATABASE_URL: DATABASE_URL
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  MSG_KEY: <use `rake newkey:msg` to generate a secret key>
  SECURE_SCHEME: HTTP
  SENDGRID_API_KEY: SENDGRID_API_KEY
  SENDGRID_FROM_EMAIL: SENDGRID_FROM_EMAIL
  LINE_OAUTH_TOKEN_URL: https://api.line.me/oauth2/v2.1/token
  LINE_CLIENT_ID: LINE_CLIENT_ID
  LINE_REDIRECT_URI: http://localhost:9292/auth/line_callback
  LINE_CLIENT_SECRET: LINE_CLIENT_SECRET
  LINE_NOTIFY_OAUTH_TOKEN_URL: https://notify-bot.line.me/oauth/token
  LINE_NOTIFY_CLIENT_ID: LINE_NOTIFY_CLIENT_ID
  LINE_NOTIFY_REDIRECT_URI: http://localhost:9292/auth/line_notify_callback
  LINE_NOTIFY_CLIENT_SECRET: LINE_NOTIFY_CLIENT_SECRET
  LINE_NOTIFY_URL: https://notify-api.line.me/api/notify
test:
  DATABASE_URL: DATABASE_URL
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  MSG_KEY: <use `rake newkey:msg` to generate a secret key>
  SECURE_SCHEME: HTTP
  SENDGRID_API_KEY: SENDGRID_API_KEY
  SENDGRID_FROM_EMAIL: SENDGRID_FROM_EMAIL
  LINE_OAUTH_TOKEN_URL: https://api.line.me/oauth2/v2.1/token
  LINE_CLIENT_ID: LINE_CLIENT_ID
  LINE_REDIRECT_URI: http://localhost:9292/auth/line_callback
  LINE_CLIENT_SECRET: LINE_CLIENT_SECRET
  LINE_NOTIFY_OAUTH_TOKEN_URL: https://notify-bot.line.me/oauth/token
  LINE_NOTIFY_CLIENT_ID: LINE_NOTIFY_CLIENT_ID
  LINE_NOTIFY_REDIRECT_URI: http://localhost:9292/auth/line_notify_callback
  LINE_NOTIFY_CLIENT_SECRET: LINE_NOTIFY_CLIENT_SECRET
  LINE_NOTIFY_URL: https://notify-api.line.me/api/notify
production:
  DATABASE_URL: <set to production DB>
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  MSG_KEY: <use `rake newkey:msg` to generate a secret key>
  SECURE_SCHEME: HTTPS
  SENDGRID_API_KEY: SENDGRID_API_KEY
  SENDGRID_FROM_EMAIL: SENDGRID_FROM_EMAIL
  LINE_OAUTH_TOKEN_URL: https://api.line.me/oauth2/v2.1/token
  LINE_CLIENT_ID: LINE_CLIENT_ID
  LINE_REDIRECT_URI: http://localhost:9292/auth/line_callback
  LINE_CLIENT_SECRET: LINE_CLIENT_SECRET
  LINE_NOTIFY_OAUTH_TOKEN_URL: https://notify-bot.line.me/oauth/token
  LINE_NOTIFY_CLIENT_ID: LINE_NOTIFY_CLIENT_ID
  LINE_NOTIFY_REDIRECT_URI: http://localhost:9292/auth/line_notify_callback
  LINE_NOTIFY_CLIENT_SECRET: LINE_NOTIFY_CLIENT_SECRET
  LINE_NOTIFY_URL: https://notify-api.line.me/api/notify