---
development:
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: 5p01Qrx4Vdhyg8/QfqegEQa2nEeJ1z1kfuFYiHZWGTI=
test:
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: slOPlE8yoDRpBUXQ3mUAK4zoiJV/usQ90s03Uy4mMQc=

production:
  DATABASE_URL: <set to production DB>
  DB_KEY: <use `rake newkey:db` to generate a secret key>