---
development:
  DATABASE_URL: DATABASE_URL
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  MSG_KEY: <use `rake newkey:msg` to generate a secret key>
  SECURE_SCHEME: HTTP
  SENDGRID_API_KEY: SENDGRID_API_KEY
  SENDGRID_FROM_EMAIL: SENDGRID_FROM_EMAIL
test:
  DATABASE_URL: DATABASE_URL
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  MSG_KEY: <use `rake newkey:msg` to generate a secret key>
  SECURE_SCHEME: HTTP
  SENDGRID_API_KEY: SENDGRID_API_KEY
  SENDGRID_FROM_EMAIL: SENDGRID_FROM_EMAIL

production:
  DATABASE_URL: <set to production DB>
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  MSG_KEY: <use `rake newkey:msg` to generate a secret key>
  SECURE_SCHEME: HTTPS
  SENDGRID_API_KEY: SENDGRID_API_KEY
  SENDGRID_FROM_EMAIL: SENDGRID_FROM_EMAIL